name: Feature Request
description: Suggest an idea for Batch Actions
labels:
  - enhancement
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What would you like to see added to or changed in Batch Actions, and why?
    validations:
      required: true
